### ISSUE TITLE
ModuleNotFoundError: No module named 'evosax.learned_eo' with Anaconda environment

### ISSUE THREAD

**Issue by abdalazizrashid** [RobertTLange/evosax#50]
Installing the latest evosax `git+https://github.com/RobertTLange/evosax.git@main` on a fresh environment yields the following import error:

```
Python 3.9.16 | packaged by conda-forge | (main, Feb  1 2023, 21:39:03) 
[GCC 11.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import evosax
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/conda/envs/inv4mat/lib/python3.9/site-packages/evosax/__init__.py", line 2, in <module>
    from .strategies import (
  File "/opt/conda/envs/inv4mat/lib/python3.9/site-packages/evosax/strategies/__init__.py", line 32, in <module>
    from .les import LES
  File "/opt/conda/envs/inv4mat/lib/python3.9/site-packages/evosax/strategies/les.py", line 7, in <module>
    from ..learned_eo.les_tools import (
ModuleNotFoundError: No module named 'evosax.learned_eo'
```
This seems to happen with Anaconda environment only.

**Comment by RobertTLange** [comment]
Hi @abdalazizrashid, Really sorry for the late reply -- was pretty busy with attending ICLR and the NeurIPS deadline. I believe this should be fixed now. At least the example colabs run correctly. Can you double check with a clean install from the main branch? Cheers and thank you for raising this, Rob
